"""att

Revision ID: 0f06b7693f1b
Revises: ce0c4cc5c635
Create Date: 2026-07-26 02:55:45.553265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f06b7693f1b'
down_revision = 'ce0c4cc5c635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baixada_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avarias', schema=None) as batch_op:
        batch_op.drop_column('baixada_at')

    # ### end Alembic commands ###
