"""USERS CREATE

Revision ID: 369672f8457d
Revises: 
Create Date: 2026-07-23 22:29:31.508908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369672f8457d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('current_jti', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('avarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('franquia', sa.String(length=100), nullable=False),
    sa.Column('embalagem', sa.String(length=100), nullable=False),
    sa.Column('tipo_avaria', sa.String(length=100), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('motorista', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avarias')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
