"""att

Revision ID: ce0c4cc5c635
Revises: fe46b3fc4508
Create Date: 2026-07-26 02:53:59.082903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0c4cc5c635'
down_revision = 'fe46b3fc4508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaria_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baixada_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaria_history', schema=None) as batch_op:
        batch_op.drop_column('baixada_at')

    # ### end Alembic commands ###
