"""ALTER PRODUTO

Revision ID: ebcb88dfd2fe
Revises: 0925eec76ca8
Create Date: 2026-07-23 23:58:35.818515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcb88dfd2fe'
down_revision = '0925eec76ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avarias', schema=None) as batch_op:
        batch_op.drop_column('franquia')
        batch_op.drop_column('embalagem')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('franquia', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('embalagem', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('embalagem')
        batch_op.drop_column('franquia')

    with op.batch_alter_table('avarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embalagem', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('franquia', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
